### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by jiyeong1004** [jiyeong1004/BATTLEGROUNDS_Mobile_India#4]
https://www.youtube.com/watch?v=A-JGoHbwjW0

**Comment by jiyeong1004** [comment]
![image](https://user-images.githubusercontent.com/51290739/122927617-052f1100-d3a4-11eb-9dc5-ff0a828a1e1c.png)

**Comment by jiyeong1004** [comment]
```CSS
section
{
    position: relative;
    width: 100%;
    height: 100vh;
    background: url(image/bg.png);
}
```

**Comment by jiyeong1004** [comment]
![image](https://user-images.githubusercontent.com/51290739/122928201-9900dd00-d3a4-11eb-838d-31c1ee3526c3.png)
background-size: cover;

**Comment by jiyeong1004** [comment]
cursor: url('image/aim.png');

![마우스커서_전](https://user-images.githubusercontent.com/51290739/122930463-fac24680-d3a6-11eb-9279-a76335bf0a87.gif)

**Comment by jiyeong1004** [comment]
cursor: url('image/aim.png'), pointer;
![마우스커서_후](https://user-images.githubusercontent.com/51290739/122931803-2f82cd80-d3a8-11eb-871a-10ea4d152d9b.gif)

**Comment by jiyeong1004** [comment]
`section:active
{
    cursor: url('image/aim_red.png'), pointer;
}`

![커서포인터](https://user-images.githubusercontent.com/51290739/122969821-0ffb9d00-d3c8-11eb-93d8-1168db93cfe7.gif)

**Comment by jiyeong1004** [comment]
![총알자국](https://user-images.githubusercontent.com/51290739/123192956-dd909380-d4de-11eb-9506-7baeb30d59d5.gif)

**Comment by jiyeong1004** [comment]
```CSS
.bullet
{
    position: absolute;
    width: 40px;
    height: 40px;
    background: url(image/hole.png);
    pointer-events: none;
}
```

**Comment by jiyeong1004** [comment]
```
.bullet
{
    position: absolute;
    width: 40px;
    height: 40px;
    background: url(image/hole.png);
    pointer-events: none;
    transform: translate(30px, 30px);
}
```

![중앙총알자국](https://user-images.githubusercontent.com/51290739/123193345-98209600-d4df-11eb-8e26-2d4b312b05ba.gif)

**Comment by jiyeong1004** [comment]
![중앙총알자국](https://user-images.githubusercontent.com/51290739/123193345-98209600-d4df-11eb-8e26-2d4b312b05ba.gif)

```
.bullet
{
    position: absolute;
    width: 40px;
    height: 40px;
    background: url(image/hole.png);
    pointer-events: none;
    transform: translate(30px, 30px);
}
```

**Comment by jiyeong1004** [comment]
![중앙총알자국](https://user-images.githubusercontent.com/51290739/123193614-12511a80-d4e0-11eb-8304-a0b70aa2d195.gif)

```CSS
.bullet
{
    position: absolute;
    width: 40px;
    height: 40px;
    background: url(image/hole.png);
    pointer-events: none;
    transform: translate(30px, 30px);
}
```

**Comment by jiyeong1004** [comment]
![blood초기_안사라짐](https://user-images.githubusercontent.com/51290739/123523983-5b80b480-d702-11eb-87eb-11346b79ee1c.gif)

```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    background: #f00;
    z-index: 1000;
    pointer-events: none;
    transform: translate(-50%, -50%);
}
```

**Comment by jiyeong1004** [comment]
![피사라짐](https://user-images.githubusercontent.com/51290739/123536619-6836f400-d766-11eb-8c96-644bd761b1b4.gif)

`.blood`에 `animation: fadeOut 4s linear infinite;` 추가

```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    background: #f00;
    z-index: 1000;
    pointer-events: none;
    transform: translate(-50%, -50%);
    animation: fadeOut 4s linear infinite;
}
@keyframes fadeOut
{
    0%, 50%
    {
        opacity: 1;
    }
    100%
    {
        opacity: 0;
    }
}
```

**Comment by jiyeong1004** [comment]
```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    background: #f00;
    z-index: 1000;
    pointer-events: none;
    transform: translate(-50%, -50%);
    animation: fadeOut 4s linear infinite;
}
```

에서 `background: #f00;` 를 삭제했습니다.

```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    z-index: 1000;
    pointer-events: none;
    transform: translate(-50%, -50%);
    animation: fadeOut 4s linear infinite;
}
```

**Comment by jiyeong1004** [comment]
<h1>Complete</h1>

![blood이미지잘나옴](https://user-images.githubusercontent.com/51290739/123587173-db04a580-d820-11eb-854e-ae6f3ae61b06.gif)

```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    z-index: 1000;
    pointer-events: none;
    transform: translate(-50%, -50%);
    animation: fadeOut 4s linear infinite;
}
```

에서 `background-size: cover;` 를 추가함

```CSS
.blood
{
    position: absolute;
    display: inline-block;
    width: 400px;
    height: 400px;
    z-index: 1000;
    background-size: cover;
    pointer-events: none;
    transform: translate(-50%, -50%);
    animation: fadeOut 4s linear infinite;
}
```
